### ISSUE TITLE
Testsuite not building on master against many PRs

### ISSUE THREAD

**Issue by wrwilliams** [dyninst/testsuite#17]
http://jenkins.dyninst.org/jenkins/job/testsuite-build/lastFailedBuild/console

When we're adding dependencies to the tests like this, they should be wrapped in a `cap_XXX` condition, so that only code that's merged in the requisite Dyninst features will try to use them in the test.

**Comment by ssunny7** [comment]
Commit 41ec24aaa0ffcea7638b75fd091ef646412fbdbf reverted by commit 70396c605d4db321cf15bf95191c2c2274eeb798.

**Comment by hainest** [comment]
The Jenkins server is no longer responding. The current master is building against new PRs without issue.
