### ISSUE TITLE
testsuite has secondary group test failures on arm64 due to testing not-yet-implemented static linking

### ISSUE THREAD

**Issue by bigtrak** [dyninst/testsuite#180]
When a test in a group fails, the entire group fails.  Dyninst does not yet implement static linking 
on arm64 / aarch64... but was running those tests.   Due to this combination, we could see many
test failures, depending on when the static linking tests were executed.

**Comment by hainest** [comment]
Just a minor nit: it's only rewriting statically-linked binaries that isn't supported. All other modes (create, attach, etc.) do work on static ARM binaries.

**Comment by bigtrak** [comment]
> Just a minor nit: it's only rewriting statically-linked binaries
> that isn't supported. All other modes (create, attach, etc.) do work
> on static ARM binaries.

That is a good point, my wording did not mention that it that way.
That is exactly the tests the config changes disable.

Bolo
