### ISSUE TITLE
exec this testsuite requires github connection?

### ISSUE THREAD

**Issue by chinyu0704** [dyninst/testsuite#183]
hi,

I wonder if I can exec this testsuite without connctiong to github, without doing some PR jobs?  I just want to check whether the dyninst is ok after building. Is this testcase suitable for me for that purpose?

sorry, English is my non mother language so I maybe misunderstood the README.
can somebody tell me ? thanks!

**Comment by hainest** [comment]
If you only want to check whether Dyninst is working, I would build and execute one or more of the [examples](https://github.com/dyninst/examples). This test suite is used to verify code changes for development.

**Comment by chinyu0704** [comment]
@hainest thanks for your reply. But the code changes refer to dyninst itself or the code(software) being dynamicly instrumented?

**Comment by hainest** [comment]
The code changes are for Dyninst, itself. It allows us developers to validate our changes to Dyninst.

**Comment by chinyu0704** [comment]
@hainest thanks for your help. I'll close this issue.
