### ISSUE TITLE
Missing v12.0.1 tag for testsuite

### ISSUE THREAD

**Issue by wcohen** [dyninst/testsuite#207]
The packaging for Fedora dyninst rpms expects that there are matching tags in both dyinst and the testsuite repositories.  There isn't a v12.0.1 tag for the testsuite that matches the v12.0.1 tag in the dyninst repository.

**Comment by hainest** [comment]
There isn't a v12.0.1 because there were no changes made to the test suite for that corresponding Dyninst release. It would be weird to have two release tags pointing to the same commit, but I suppose we could if this is really a hard failure point for the Fedora packaging workflow.

I was unaware that Fedora was publishing rpms for the test suite. It's really not intended to be used by anyone who isn't a developer. Are those rpms available for public consumption?

**Comment by wcohen** [comment]
In general for distribution it is good to have easily accessible testsuites.  For example there are testsuite subpackage rpms for papi, systemtap, pcp, and rr.  This is particular true for packages that are very architecture specific.  The developer may be working on x86 and not detect an issue until QE is testing the package on aarch64 or powerpc64.

Having the testsuite built and packaged at the same time as package itself is very useful for QE testing and for package maintainer to make sure that the package is working as expected.  There is a matching dyninst-testsuite rpm that can be installed and run to check that everything is good with dyninst.  For Fedora the testsuite rpm is easily available.  For RHEL the testsuite package isn't part of the normal compose provided outside of Red Hat.

It isn't a hard failure point for the Fedora packaging workflow to not have a matching testsuite tag, but it will make things much more sane to have a matching tag in the testsuite.  No having to fiddle with the version difference between dyninst and testsuite in the spec file build.  Also avoid the possible point of failure where the maintainer forgets to update the testsuite and newly added testsuite tests are omitted testing some new dynisnt functionality.

Would creating a testsuite tag matching the dyninst release tag be difficult?

**Comment by hainest** [comment]
There is a v12.0.1 tag now. I've added this to our release instructions, so we should stay synchronized with Dyninst release numbers going forward.
