### ISSUE TITLE
arm64 test_symtab_ser_funcs test fails

### ISSUE THREAD

**Issue by ikitayama** [dyninst/testsuite#22]
Observed on arm64, this prevents from executing all the tests under the src/symtab directory
using the -symtab option of the test_driver script. 
```
$ ./test_driver -test test_symtab_ser_funcs
test_driver: /home/itaru.kitayama/projects/testsuite/src/test_lib.C:502: bool shouldRunTest(RunGroup*, TestInfo*): Assertion `test->results[i] == UNKNOWN || test->results[i] == PASSED' failed.
Aborted (core dumped)
```

**Comment by ikitayama** [comment]
As of this writing, some of the tests are known to work with the SymtabAPI on arm64.

**test_add_symbols** all passed
**test_line_info** all passed
**test_lookup_func** all passed
**test_lookup_var** all passed
**test_module** all passed
**test_relocations** all passed
**test_type_info** all passed

**Comment by wrwilliams** [comment]
test_symtab_ser_funcs should be disabled/deleted everywhere, as that functionality no longer exists. I'll double-check that and regenerate the spec files.
