### ISSUE TITLE
Testsuite (master branch) build failure  

### ISSUE THREAD

**Issue by ikitayama** [dyninst/testsuite#23]
Anyone seen this or similar on Ubuntu?
 
```
[ 27%] Built target test_snip_remove.dyn_gcc_64_none_none
[ 27%] Built target test3_7.dyn_gcc_64_none_none
[ 27%] Built target dyninst_group_test.dyn_gcc_64_none_none
[ 27%] Built target test1_19.dyn_gcc_64_none_none
[ 27%] Linking C executable test_mem_1.dyn_gcc_64_none_none
/usr/bin/ld: CMakeFiles/test_mem_1.dyn_gcc_64_none_none.dir/__/__/__/__/__/__/__/src/dyninst/test6LS-x86_64.s.o: relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
x86_64-unknown-linux2.4/dyninst/gcc/64/dyn/none/none/CMakeFiles/test_mem_1.dyn_gcc_64_none_none.dir/build.make:190: recipe for target 'x86_64-unknown-linux2.4/dyninst/gcc/64/dyn/none/none/test_mem_1.dyn_gcc_64_none_none' failed
make[2]: *** [x86_64-unknown-linux2.4/dyninst/gcc/64/dyn/none/none/test_mem_1.dyn_gcc_64_none_none] Error 1
CMakeFiles/Makefile2:8928: recipe for target 'x86_64-unknown-linux2.4/dyninst/gcc/64/dyn/none/none/CMakeFiles/test_mem_1.dyn_gcc_64_none_none.dir/all' failed
make[1]: *** [x86_64-unknown-linux2.4/dyninst/gcc/64/dyn/none/none/CMakeFiles/test_mem_1.dyn_gcc_64_none_none.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by ikitayama** [comment]
Skipping `test_mem_*` tests on x86_64 linux helps to build testsuite. Verified on Ubuntu, but think it's true on Fedora as well.

**Comment by wrwilliams** [comment]
The test_mem_* tests rely on hand-rolled assembly; they should be revised to exclude PIC/PIE linking variants (and also to ignore optimization levels and different compilers) in the specification.

**Comment by ikitayama** [comment]
@wrwilliams I'm not familiar enough to make the changes in the specification, do you have time to do it?

**Comment by wrwilliams** [comment]
Not today, I don't, but I can take a shot next week. (And this is proving a bit more hairy than I'd initially thought, which is why I don't have time to implement.)

**Comment by ikitayama** [comment]
@wrwilliams that's great!. In the mean time, I've verified this branch:

https://github.com/ikitayama/testsuite/commits/my9.3.0

can be built on the x86 Ubuntu 16.10. I didn't execute all, but the test_stack_1 test ran ok.

**Comment by hainest** [comment]
@mxz297 Necroing because it's related to #40.

**Comment by hainest** [comment]
Moved this discussion to #40.
