### ISSUE TITLE
Bump Boost version

### ISSUE THREAD

**Issue by hainest** [dyninst/testsuite#36]
We are compiling on 1.68 fine, but need https://github.com/dyninst/dyninst/pull/541 to compile with 1.69

**Comment by hainest** [comment]
Include @mxz297

**Comment by sashanicolas** [comment]
I knew we needed at least 1.60
But if we need to require a newer version, https://github.com/dyninst/dyninst/blob/master/cmake/packages.cmake#L105 should reflect that.

**Comment by mxz297** [comment]
@hainest Are there any source code of the test suite needed to be changed for bumping boost version?

**Comment by hainest** [comment]
I'm not sure. I haven't tested that yet. It's on my todo list, though.
