### ISSUE TITLE
power_decode test failing

### ISSUE THREAD

**Issue by hainest** [dyninst/testsuite#37]
power_decode                      none 64  disk     NA      dynamic nonPIC  FAILED (Running Test)
power_decode                      none 32  disk     NA      dynamic nonPIC  FAILED (Running Test)

I ran the tests using "./runTests -all -log all.log".

@sashanicolas could you take a look?

**Comment by mxz297** [comment]
My latest commit is for this issue. Can you give it a try?

**Comment by sashanicolas** [comment]
Passing at `x86_64` and `power`, not set to run on `aarch64`.
